export const INCOME = 1760
export const BONUS = 1000

export const INITIAL_WEEKS = [
  {
    id: 'w1',
    date: 'March 27, 2025',
    label: 'End of March — Bonus Month',
    type: 'bonus',
    bonusIncome: BONUS,
    bonusExpense: { name: 'Rent (1st)', amount: 1000 },
    note: 'Runs -$27 vs original — birthday + all bills hit at once.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Tilt', amount: 300 },
      { id: 'e4', name: 'Electricity', amount: 209 },
      { id: 'e5', name: 'Tommy Vet', amount: 60 },
      { id: 'e6', name: 'Target', amount: 50 },
      { id: 'e7', name: 'Jeep Insurance', amount: 93 },
      { id: 'e8', name: 'Birthday (hotel + expenses)', amount: 600 },
      { id: 'e9', name: 'Van Insurance', amount: 55 },
      { id: 'e10', name: 'Progressive Leasing', amount: 20 },
    ],
  },
  {
    id: 'w2',
    date: 'April 3, 2025',
    label: '',
    type: 'normal',
    note: 'Kay clears Apr 6 — slight timing buffer.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Discover (min)', amount: 100 },
      { id: 'e4', name: 'CareCredit AutoPay', amount: 100 },
      { id: 'e5', name: 'CashApp', amount: 350 },
      { id: 'e6', name: 'Rent (half)', amount: 735 },
      { id: 'e7', name: 'Kay', amount: 100 },
    ],
  },
  {
    id: 'w3',
    date: 'April 10, 2025',
    label: 'Wisdom Teeth Savings Push',
    type: 'savings',
    note: '',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Jeep Payment', amount: 528 },
      { id: 'e4', name: 'Wisdom Teeth Fund', amount: 800 },
    ],
  },
  {
    id: 'w4',
    date: 'April 17, 2025',
    label: 'Progressive Leasing Payoff',
    type: 'payoff',
    note: 'Progressive Leasing done — frees $20/mo going forward.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Van Payment', amount: 500 },
      { id: 'e4', name: 'Van Insurance', amount: 55 },
      { id: 'e5', name: 'Verizon', amount: 250 },
      { id: 'e6', name: 'Progressive Leasing PAYOFF', amount: 300 },
      { id: 'e7', name: 'CashApp', amount: 200 },
    ],
  },
  {
    id: 'w5',
    date: 'April 24, 2025',
    label: 'End of April — Bonus Month',
    type: 'bonus',
    bonusIncome: BONUS,
    bonusExpense: { name: 'Rent (remainder)', amount: 1000 },
    note: 'Runs -$28 vs $1,760 — watch this one.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Rent (half)', amount: 735 },
      { id: 'e4', name: 'Tommy Vet', amount: 60 },
      { id: 'e5', name: 'Jeep Insurance', amount: 93 },
      { id: 'e6', name: 'Wisdom Teeth Fund', amount: 500 },
    ],
  },
  {
    id: 'w6',
    date: 'May 1, 2025',
    label: 'Wisdom Teeth Savings Push',
    type: 'savings',
    note: 'Surgery one week away — final savings push.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Electricity', amount: 250 },
      { id: 'e4', name: 'Tommy Vet', amount: 60 },
      { id: 'e5', name: 'Target', amount: 50 },
      { id: 'e6', name: 'Discover (min)', amount: 100 },
      { id: 'e7', name: 'Jeep Insurance', amount: 93 },
      { id: 'e8', name: 'Wisdom Teeth Fund', amount: 500 },
      { id: 'e9', name: 'Wifi', amount: 53 },
      { id: 'e10', name: 'Kay', amount: 100 },
    ],
  },
  {
    id: 'w7',
    date: 'May 8, 2025',
    label: "Lisa's Wisdom Teeth Surgery",
    type: 'surgery',
    note: '~$3,000 saved across prior weeks covers surgery costs.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'CareCredit AutoPay (min)', amount: 90 },
      { id: 'e4', name: 'Wisdom Teeth Surgery', amount: 1200 },
    ],
  },
  {
    id: 'w8',
    date: 'May 15, 2025',
    label: 'Post-Surgery — CareCredit Attack Begins',
    type: 'payoff',
    note: 'CareCredit extra payments start May 22.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Van Payment', amount: 500 },
      { id: 'e4', name: 'Verizon', amount: 250 },
      { id: 'e5', name: 'Jeep Payment', amount: 528 },
    ],
  },
  {
    id: 'w9',
    date: 'May 22, 2025',
    label: 'CareCredit Extra Payment',
    type: 'payoff',
    note: 'CareCredit ~$3,813 combined. After this: ~$2,723.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Van Insurance', amount: 55 },
      { id: 'e4', name: 'CareCredit EXTRA PAYMENT', amount: 1000 },
    ],
  },
  {
    id: 'w10',
    date: 'May 29, 2025',
    label: 'End of May — Bonus Month',
    type: 'bonus',
    bonusIncome: BONUS,
    bonusExpense: { name: 'Rent (remainder)', amount: 1000 },
    note: '',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Rent (half)', amount: 735 },
      { id: 'e4', name: 'Electricity', amount: 250 },
      { id: 'e5', name: 'Jeep Insurance', amount: 93 },
      { id: 'e6', name: 'Wifi', amount: 53 },
      { id: 'e7', name: 'Tommy Vet', amount: 60 },
      { id: 'e8', name: 'Target', amount: 50 },
    ],
  },
  {
    id: 'w11',
    date: 'June 5, 2025',
    label: 'CareCredit Extra Payment',
    type: 'payoff',
    note: 'CareCredit down to ~$1,633. Kay nearly done.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Discover (min)', amount: 100 },
      { id: 'e4', name: 'CareCredit EXTRA PAYMENT', amount: 1000 },
      { id: 'e5', name: 'Kay', amount: 100 },
    ],
  },
  {
    id: 'w12',
    date: 'June 12, 2025',
    label: 'CareCredit Final Push',
    type: 'payoff',
    note: 'CareCredit ~$1,283 remaining after this.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Verizon', amount: 250 },
      { id: 'e4', name: 'Jeep Payment', amount: 528 },
      { id: 'e5', name: 'CareCredit EXTRA PAYMENT', amount: 350 },
    ],
  },
  {
    id: 'w13',
    date: 'June 19, 2025',
    label: 'CareCredit — Finish It',
    type: 'payoff',
    note: 'CareCredit paid off. Pivot fully to Discover.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Van Payment', amount: 500 },
      { id: 'e4', name: 'Van Insurance', amount: 55 },
      { id: 'e5', name: 'CareCredit PAYOFF', amount: 805 },
    ],
  },
  {
    id: 'w14',
    date: 'June 26, 2025',
    label: 'End of June — Bonus Month',
    type: 'bonus',
    bonusIncome: BONUS,
    bonusExpense: { name: 'Rent (remainder)', amount: 1000 },
    note: 'Discover paydown begins in earnest.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Rent (half)', amount: 735 },
      { id: 'e4', name: 'Electricity', amount: 250 },
      { id: 'e5', name: 'Wifi', amount: 53 },
      { id: 'e6', name: 'Tommy Vet', amount: 60 },
      { id: 'e7', name: 'Target', amount: 50 },
      { id: 'e8', name: 'Jeep Insurance', amount: 93 },
      { id: 'e9', name: 'Discover EXTRA PAYMENT', amount: 119 },
    ],
  },
  {
    id: 'w15',
    date: 'July 3, 2025',
    label: 'Discover Full Attack Mode',
    type: 'payoff',
    note: 'Most bills hit other weeks — throw everything at Discover.',
    expenses: [
      { id: 'e1', name: 'Weed', amount: 100 },
      { id: 'e2', name: 'Food', amount: 300 },
      { id: 'e3', name: 'Discover EXTRA PAYMENT', amount: 1260 },
    ],
  },
]

export const DEBTS = [
  { name: 'CareCredit – Lisa', balance: 2346, apr: '0% promo', min: 90, note: 'Deferred interest — kill before promo ends', priority: 1 },
  { name: 'CareCredit – Joe',  balance: 1467, apr: '0% promo', min: 0,  note: 'Treat as one ~$3,813 combined balance', priority: 1 },
  { name: 'Discover',          balance: 3841, apr: '22.5%',   min: 100, note: 'Pay to $1,000 then min while attacking Van', priority: 2 },
  { name: 'Van Loan',          balance: 15600, apr: '~6.5%',  min: 500, note: 'Lowest rate — attack last', priority: 3 },
  { name: 'Kay',               balance: 550,   apr: '33%',    min: 100, note: '$100/mo min until done — nearly there', priority: 0 },
]
